package studio

import (
	"strings"
	"testing"
)

const canonicalRefundConstants = `// Package domain holds the refund-flow domain's vocabulary and contracts.
//
// Generated by kiff-studio. The constants block names every
// domain identifier the framework cares about — adapter,
// entity, events, states, actions, permissions — in one
// place, per the framework's conventions.
package domain

import "github.com/kiff/kiff/pkg/kiff/permission"

const (
	AdapterRefundFlow = "refundflow"

	EntityOrder = "Order"

	EventOrderReadyForRefund = "ORDER_READY_FOR_REFUND"
	EventOrderRefunded = "ORDER_REFUNDED"

	StateReadyForRefund = "READY_FOR_REFUND"
	StateRefunded = "REFUNDED"

	ActionIssueRefund = "ISSUE_REFUND"

	PermRefundFlowIssueRefund permission.Permission = "refund-flow.issue_refund"
	PermRefundFlowIssueRefundApprove permission.Permission = "refund-flow.issue_refund.approve"
)
`

func TestBuildConstants_MatchesCanonicalRefundShape(t *testing.T) {
	t.Parallel()
	got, err := BuildConstants(canonicalRefundBlueprint(), "domain")
	if err != nil {
		t.Fatalf("BuildConstants: %v", err)
	}
	if string(got) != canonicalRefundConstants {
		t.Fatalf("constants mismatch.\n--- got ---\n%s\n--- want ---\n%s", string(got), canonicalRefundConstants)
	}
}

func TestBuildConstants_RejectsBadPackageName(t *testing.T) {
	t.Parallel()
	_, err := BuildConstants(canonicalRefundBlueprint(), "9bad")
	if err == nil || !strings.Contains(err.Error(), "valid Go identifier") {
		t.Fatalf("expected invalid-identifier error, got %v", err)
	}
}

func TestBuildConstants_RejectsInvalidBlueprint(t *testing.T) {
	t.Parallel()
	bp := canonicalRefundBlueprint()
	bp.Domain = ""
	_, err := BuildConstants(bp, "domain")
	if err == nil || !strings.Contains(err.Error(), "domain") {
		t.Fatalf("expected validation error, got %v", err)
	}
}
