package studio

import (
	"fmt"
	"sort"
	"strings"
)

// BuildConstants returns Go source for a domain-package constants
// block matching the framework's conventions (see
// docs/conventions.md §"Constants block"). The output is the
// canonical "every domain identifier in one block" shape — adapter
// name, entity, events, states, actions, permissions — with the
// permission constants typed as permission.Permission so the
// framework's action contracts can use them directly.
//
// packageName is the Go package name the file declares (commonly
// "domain"). It must be a valid Go identifier.
//
// Output is byte-deterministic: identical Blueprint and packageName
// always produce identical bytes. The file is import-correct and
// compiles in isolation when paired with the framework dependency.
func BuildConstants(b Blueprint, packageName string) ([]byte, error) {
	if err := b.Validate(); err != nil {
		return nil, fmt.Errorf("studio.BuildConstants: %w", err)
	}
	if !isGoIdent(packageName) {
		return nil, fmt.Errorf("studio.BuildConstants: package name %q is not a valid Go identifier", packageName)
	}

	var sb strings.Builder
	sb.WriteString("// Package ")
	sb.WriteString(packageName)
	sb.WriteString(" holds the ")
	sb.WriteString(b.Domain)
	sb.WriteString(" domain's vocabulary and contracts.\n")
	sb.WriteString("//\n")
	sb.WriteString("// Generated by kiff-studio. The constants block names every\n")
	sb.WriteString("// domain identifier the framework cares about — adapter,\n")
	sb.WriteString("// entity, events, states, actions, permissions — in one\n")
	sb.WriteString("// place, per the framework's conventions.\n")
	sb.WriteString("package ")
	sb.WriteString(packageName)
	sb.WriteString("\n\n")

	sb.WriteString(`import "github.com/kiff/kiff/pkg/kiff/permission"`)
	sb.WriteString("\n\n")

	sb.WriteString("const (\n")

	// Adapter — the canonical name is the domain itself, lowercase
	// without hyphens (adapter names are single-word per the
	// conventions). camelToSnake on a hyphenated name strips the
	// hyphens for us via the underscore replacement.
	adapterName := stripHyphens(b.Domain)
	sb.WriteString(fmt.Sprintf("\tAdapter%s = %q\n\n", goExportName(b.Domain), adapterName))

	// Entity.
	sb.WriteString(fmt.Sprintf("\tEntity%s = %q\n\n", b.Entity, b.Entity))

	// Events. One Event<Name> per event.
	for _, e := range b.Events {
		sb.WriteString(fmt.Sprintf("\tEvent%s = %q\n", goExportFromUpperSnake(e), e))
	}
	sb.WriteString("\n")

	// States. One State<Name> per state.
	for _, s := range b.States {
		sb.WriteString(fmt.Sprintf("\tState%s = %q\n", goExportFromUpperSnake(s), s))
	}
	sb.WriteString("\n")

	// Actions. One Action<Name> per action.
	for _, a := range b.Actions {
		sb.WriteString(fmt.Sprintf("\tAction%s = %q\n", goExportFromUpperSnake(a.Name), a.Name))
	}
	sb.WriteString("\n")

	// Permissions. Typed as permission.Permission so contracts use
	// them directly. Emit one Perm<Name> per unique permission across
	// all actions, sorted for determinism.
	permList := uniqueSortedPermissions(b)
	for _, p := range permList {
		sb.WriteString(fmt.Sprintf("\tPerm%s permission.Permission = %q\n", goExportFromPerm(p), p))
	}

	sb.WriteString(")\n")

	return []byte(sb.String()), nil
}

// stripHyphens, goExportName, goExportFromUpperSnake,
// goExportFromPerm, and isGoIdent are defined in naming.go
// alongside the other convention helpers (the predicate
// functions like isUpperSnake / isDottedLower). Keeping all
// naming-shaped helpers in one file makes them easy to find from
// any caller.

// uniqueSortedPermissions returns every permission referenced by
// the Blueprint's actions (including .approve counterparts) plus
// any role permission that's not on an action. Sorted lexicographically.
func uniqueSortedPermissions(b Blueprint) []string {
	seen := make(map[string]struct{})
	for _, a := range b.Actions {
		for _, p := range a.RequiredPermissions {
			seen[p] = struct{}{}
		}
	}
	for _, perms := range b.Roles {
		for _, p := range perms {
			seen[p] = struct{}{}
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}
