package studio

import (
	"fmt"
	"strings"
)

// BuildConstants returns Go source for a domain-package constants
// block matching the framework's conventions (see
// docs/conventions.md §"Constants block"). The output is the
// canonical "every domain identifier in one block" shape — adapter
// name, entity, events, states, actions, permissions — with the
// permission constants typed as permission.Permission so the
// framework's action contracts can use them directly.
//
// packageName is the Go package name the file declares (commonly
// "domain"). It must be a valid Go identifier.
//
// Output is byte-deterministic: identical Blueprint and packageName
// always produce identical bytes. The file is import-correct and
// compiles in isolation when paired with the framework dependency.
func BuildConstants(b Blueprint, packageName string) ([]byte, error) {
	if err := b.Validate(); err != nil {
		return nil, fmt.Errorf("studio.BuildConstants: %w", err)
	}
	if !isGoIdent(packageName) {
		return nil, fmt.Errorf("studio.BuildConstants: package name %q is not a valid Go identifier", packageName)
	}

	var sb strings.Builder
	sb.WriteString("// Package ")
	sb.WriteString(packageName)
	sb.WriteString(" holds the ")
	sb.WriteString(b.Domain)
	sb.WriteString(" domain's vocabulary and contracts.\n")
	sb.WriteString("//\n")
	sb.WriteString("// Generated by kiff-studio. The constants block names every\n")
	sb.WriteString("// domain identifier the framework cares about — adapter,\n")
	sb.WriteString("// entity, events, states, actions, permissions — in one\n")
	sb.WriteString("// place, per the framework's conventions.\n")
	sb.WriteString("package ")
	sb.WriteString(packageName)
	sb.WriteString("\n\n")

	sb.WriteString(`import "github.com/kiffhq/kiff/pkg/kiff/permission"`)
	sb.WriteString("\n\n")

	sb.WriteString("const (\n")

	// Adapter — the canonical name is the domain itself, lowercase
	// without hyphens (adapter names are single-word per the
	// conventions). camelToSnake on a hyphenated name strips the
	// hyphens for us via the underscore replacement.
	adapterName := stripHyphens(b.Domain)
	sb.WriteString(fmt.Sprintf("\tAdapter%s = %q\n\n", goExportName(b.Domain), adapterName))

	// Entity.
	sb.WriteString(fmt.Sprintf("\tEntity%s = %q\n\n", b.Entity, b.Entity))

	// Events. One Event<Name> per event.
	for _, e := range b.Events {
		sb.WriteString(fmt.Sprintf("\tEvent%s = %q\n", goExportFromUpperSnake(e), e))
	}
	sb.WriteString("\n")

	// States. One State<Name> per state.
	for _, s := range b.States {
		sb.WriteString(fmt.Sprintf("\tState%s = %q\n", goExportFromUpperSnake(s), s))
	}
	sb.WriteString("\n")

	// Actions. One Action<Name> per action.
	for _, a := range b.Actions {
		sb.WriteString(fmt.Sprintf("\tAction%s = %q\n", goExportFromUpperSnake(a.Name), a.Name))
	}
	sb.WriteString("\n")

	// Permissions. Typed as permission.Permission so contracts use
	// them directly. Emit one Perm<Name> per unique permission across
	// all actions, sorted for determinism.
	permList := uniqueSortedPermissions(b)
	for _, p := range permList {
		sb.WriteString(fmt.Sprintf("\tPerm%s permission.Permission = %q\n", goExportFromPerm(p), p))
	}

	sb.WriteString(")\n")

	return []byte(sb.String()), nil
}

// stripHyphens is the small helper that turns "refund-flow" into
// "refundflow" for the adapter name. Adapter names per the
// conventions are single-word lowercase; we strip hyphens rather
// than refusing hyphenated domain names, because the YAML's
// `domain` field accepts hyphens.
func stripHyphens(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '-' {
			continue
		}
		out = append(out, s[i])
	}
	return string(out)
}

// goExportName turns a hyphenated lowercase string into
// PascalCase: "refund-flow" -> "RefundFlow". Used to derive Go
// identifier names from domain-level names.
func goExportName(s string) string {
	out := make([]byte, 0, len(s))
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '-' || c == '_' {
			upper = true
			continue
		}
		if upper && c >= 'a' && c <= 'z' {
			out = append(out, c-('a'-'A'))
		} else {
			out = append(out, c)
		}
		upper = false
	}
	return string(out)
}

// goExportFromUpperSnake turns "ORDER_READY_FOR_REFUND" into
// "OrderReadyForRefund". Used to derive Go const names from
// UPPER_SNAKE_CASE event/state/action names.
func goExportFromUpperSnake(s string) string {
	out := make([]byte, 0, len(s))
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			// Already uppercase in UPPER_SNAKE_CASE.
			out = append(out, c)
			upper = false
			continue
		}
		// Convert subsequent letters to lowercase.
		if c >= 'A' && c <= 'Z' {
			out = append(out, c+('a'-'A'))
		} else {
			out = append(out, c)
		}
	}
	return string(out)
}

// goExportFromPerm turns "refund-flow.issue_refund.approve" into
// "RefundFlowIssueRefundApprove". Used to derive Go const names
// from dotted.lowercase permission strings.
func goExportFromPerm(s string) string {
	out := make([]byte, 0, len(s))
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '-' || c == '_' || c == '.' {
			upper = true
			continue
		}
		if upper && c >= 'a' && c <= 'z' {
			out = append(out, c-('a'-'A'))
		} else {
			out = append(out, c)
		}
		upper = false
	}
	return string(out)
}

// uniqueSortedPermissions returns every permission referenced by
// the Blueprint's actions (including .approve counterparts) plus
// any role permission that's not on an action. Sorted lexicographically.
func uniqueSortedPermissions(b Blueprint) []string {
	seen := make(map[string]struct{})
	for _, a := range b.Actions {
		for _, p := range a.RequiredPermissions {
			seen[p] = struct{}{}
		}
	}
	for _, perms := range b.Roles {
		for _, p := range perms {
			seen[p] = struct{}{}
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// isGoIdent reports whether s is a valid Go identifier:
// non-empty, starts with a letter or underscore, contains only
// letters, digits, and underscores. Used to validate user-provided
// package names before inserting them into generated source.
func isGoIdent(s string) bool {
	if s == "" {
		return false
	}
	c := s[0]
	if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_') {
		return false
	}
	for i := 1; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z':
		case c >= 'A' && c <= 'Z':
		case c >= '0' && c <= '9':
		case c == '_':
		default:
			return false
		}
	}
	return true
}
