package studio

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// Scaffold is the multi-file artifact set "download as kiff
// new shape" consumers render. The keys are POSIX-style relative
// paths from the scaffold's root; the values are file contents.
//
// Mirrors the layout of `kiff new -template=agentic-ops` (Brick
// 22), minus the agent/ Python harness and the demo scripts —
// those are out of scope for v0.1, which targets the Go runtime
// + domain layer only. v0.2 may extend the scaffold to include
// them.
//
// The map is intentionally ordered by Files's keys when iterated;
// callers who need byte-stable iteration can sort before writing
// to disk. The Scaffold values themselves are byte-deterministic
// for a given Blueprint and modulePath.
type Scaffold struct {
	Files map[string][]byte
}

// BuildScaffold returns a Scaffold parameterized by the user's
// Go module path. The output mirrors `kiff new
// -template=agentic-ops` for the same canonical input — same
// file layout, same package shape, same wiring. A consumer
// (Cloud's "download my domain" path, the kiff CLI's template
// rendering) writes Scaffold.Files to disk verbatim.
//
// modulePath is the user's Go module path (e.g.
// "github.com/acme/orders"). It must be a non-empty, valid Go
// module path; the package does not deeply validate the format
// beyond non-empty.
//
// The scaffold contains:
//
//   - go.mod                                 (module, framework dep)
//   - cmd/server/main.go                    (entry point)
//   - internal/domain/<domain>.go           (constants + executors)
//   - internal/domain/<domain>_test.go      (3 test cases)
//   - internal/domain/kiff.yaml             (YAML spec)
//
// The domain file's name comes from the Blueprint's Domain field,
// hyphens stripped and lowercased: "refund-flow" → "refundflow.go".
func BuildScaffold(b Blueprint, modulePath string) (Scaffold, error) {
	if err := b.Validate(); err != nil {
		return Scaffold{}, fmt.Errorf("studio.BuildScaffold: %w", err)
	}
	if strings.TrimSpace(modulePath) == "" {
		return Scaffold{}, fmt.Errorf("studio.BuildScaffold: module path is required")
	}

	yaml, err := BuildYAML(b)
	if err != nil {
		return Scaffold{}, err
	}
	constants, err := BuildConstants(b, "domain")
	if err != nil {
		return Scaffold{}, err
	}
	executors, err := BuildExecutorStub(b, "domain")
	if err != nil {
		return Scaffold{}, err
	}
	tests, err := BuildTestScaffold(b, "domain")
	if err != nil {
		return Scaffold{}, err
	}

	gomod, err := renderGoMod(modulePath)
	if err != nil {
		return Scaffold{}, err
	}
	mainGo, err := renderMain(b, modulePath)
	if err != nil {
		return Scaffold{}, err
	}

	domainFile := stripHyphens(b.Domain)

	files := map[string][]byte{
		"go.mod":             gomod,
		"cmd/server/main.go": mainGo,
		"internal/domain/" + domainFile + "_constants.go": constants,
		"internal/domain/" + domainFile + ".go":           executors,
		"internal/domain/" + domainFile + "_test.go":      tests,
		"internal/domain/kiff.yaml":                       yaml,
	}
	return Scaffold{Files: files}, nil
}

// goModTemplate is a tiny template for the scaffold's go.mod.
// The framework's version pins to the latest stable v0.1.x.
const goModTemplate = `module {{.ModulePath}}

go 1.23.0

require github.com/kiff/kiff v0.1.0
`

func renderGoMod(modulePath string) ([]byte, error) {
	tpl, err := template.New("go.mod").Parse(goModTemplate)
	if err != nil {
		return nil, fmt.Errorf("renderGoMod parse: %w", err)
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, map[string]string{"ModulePath": modulePath}); err != nil {
		return nil, fmt.Errorf("renderGoMod execute: %w", err)
	}
	return buf.Bytes(), nil
}

// mainTemplate is the cmd/server/main.go starter. It builds the
// domain runtime, wraps it in the framework's optional httpapi
// handler, and serves on :8080. Mirrors the agentic-ops template
// shape; user is expected to swap the address and add their
// auth middleware.
const mainTemplate = `// Generated by kiff-studio. The cmd/server entry point wires
// the domain runtime, wraps it in the framework's optional HTTP
// API, and serves locally. Add auth, observability, and storage
// adapters as the application grows; this skeleton is the
// "first run" shape.
package main

import (
	"log"
	"net/http"

	"github.com/kiff/kiff/pkg/kiff/httpapi"

	"{{.ModulePath}}/internal/domain"
)

func main() {
	rt, err := domain.NewRuntime()
	if err != nil {
		log.Fatalf("domain.NewRuntime: %v", err)
	}
	handler := httpapi.NewHandler(rt)
	log.Println("kiff server listening on :8080")
	if err := http.ListenAndServe(":8080", handler); err != nil {
		log.Fatalf("http.ListenAndServe: %v", err)
	}
}
`

func renderMain(b Blueprint, modulePath string) ([]byte, error) {
	tpl, err := template.New("main.go").Parse(mainTemplate)
	if err != nil {
		return nil, fmt.Errorf("renderMain parse: %w", err)
	}
	var buf bytes.Buffer
	data := map[string]string{
		"ModulePath": modulePath,
		"Domain":     b.Domain,
	}
	if err := tpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("renderMain execute: %w", err)
	}
	return buf.Bytes(), nil
}
